# Generated by Django 4.1.5 on 2023-03-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(max_length=50)),
                ('sunrise', models.TimeField()),
                ('sunset', models.TimeField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('rain', models.CharField(max_length=100)),
                ('pressure', models.FloatField()),
            ],
        ),
    ]
