# Generated by Django 4.1.5 on 2023-03-31 03:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 3, 41, 10, 76241, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='weather',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
