# Generated by Django 4.1.5 on 2023-03-31 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_weather_date_time_weather_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 3, 42, 20, 957655, tzinfo=datetime.timezone.utc)),
        ),
    ]
