# Generated by Django 4.1.5 on 2023-04-01 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_weather_wind_direction_weather_wind_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='lon',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weather',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 1, 8, 18, 19, 386288, tzinfo=datetime.timezone.utc)),
        ),
    ]
